# Generated by Django 5.1.6 on 2025-04-18 07:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_budget_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget Allocation', 'verbose_name_plural': 'Budget Allocations'},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocated_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('OPS', 'Operations'), ('IT', 'IT & Systems Management'), ('SALES', 'Sales and Revenue Management')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets_allocated', to=settings.AUTH_USER_MODEL, verbose_name='Allocated By'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets_received', to=settings.AUTH_USER_MODEL, verbose_name='Allocated To'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_level',
            field=models.CharField(choices=[('organization', 'Organization Level'), ('department', 'Department Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
