# Generated by Django 5.1.6 on 2025-04-18 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_budget_options_remove_budget_allocated_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_level', models.CharField(choices=[('organization', 'Organization Budget'), ('department', 'Department Budget')], max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(limit_choices_to={'role__in': ['admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(limit_choices_to={'role__in': ['manager', 'department_head']}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_allocations_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_level', models.CharField(choices=[('organization', 'Organization Level'), ('department', 'Department Level')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('OPS', 'Operations'), ('IT', 'IT & Systems Management'), ('SALES', 'Sales and Revenue Management')], max_length=20, null=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(limit_choices_to={'role__in': ['manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_allocations_made', to=settings.AUTH_USER_MODEL, verbose_name='Allocated By')),
                ('allocated_to', models.ForeignKey(limit_choices_to={'role__in': ['department_head']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_allocations_received', to=settings.AUTH_USER_MODEL, verbose_name='Allocated To')),
            ],
            options={
                'verbose_name': 'Manager Budget Allocation',
                'verbose_name_plural': 'Manager Budget Allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
