# Generated by Django 5.1.6 on 2025-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
