# Generated by Django 5.1.6 on 2025-03-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_admin_dashboard', 'Can view admin dashboard'), ('view_manager_dashboard', 'Can view manager dashboard'), ('view_department_dashboard', 'Can view department dashboard'), ('manage_users', 'Can manage users'), ('approve_budgets', 'Can approve budgets'), ('view_reports', 'Can view financial reports')]},
        ),
    ]
