# Generated by Django 5.1.6 on 2025-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('OPS', 'Operations'), ('IT', 'Information Technology'), ('SALES', 'Sales & Revenue Management')], editable=False, max_length=30),
        ),
    ]
