# Generated by Django 5.1.6 on 2025-05-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_income_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='status',
        ),
        migrations.RemoveField(
            model_name='income',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='verified_by',
        ),
    ]
