# Generated by Django 5.1.6 on 2025-03-06 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('department_head', 'Department Head')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('income', 'Income Breakdown'), ('savings', 'Savings & Investments'), ('fixed_expenses', 'Fixed Expenses'), ('variable_expenses', 'Variable Expenses')], max_length=50)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_budgets', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
